using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PointsUnlockForEachLevel : MonoBehaviour
{
    public int wa1Unlock;
    public int wa2Unlock;
    public int wa3Unlock;
    public int wa4Unlock;
    public int wa5Unlock;
    public int wa6Unlock;
    public int wa7Unlock;
    public int wa8Unlock;
    public int wa9Unlock;
    public int wa10Unlock;
    public int wa11Unlock;
    public int wa12Unlock;
    public int wa13Unlock;
    public int wa14Unlock;
    public int wa15Unlock;
    public int wa16Unlock;
    public int wa17Unlock;
    public int wa18Unlock;
    public int wa19Unlock;
    public int wa20Unlock;
    public int wa21Unlock;
    public int wa22Unlock;
    public int wa23Unlock;
    public int wa24Unlock;
    public int wa25Unlock;
    public int wa26Unlock;
    public int wa27Unlock;
    public int wa28Unlock;

    public int wn1Unlock;
    public int wn2Unlock;
    public int wn3Unlock;
    public int wn4Unlock;
    public int wn5Unlock;
    public int wn6Unlock;
    public int wn7Unlock;
    public int wn8Unlock;
    public int wn9Unlock;
    public int wn10Unlock;
    public int wn11Unlock;

    public int pa1Unlock;
    public int pa2Unlock;
    public int pa3Unlock;
    public int pa4Unlock;
    public int pa5Unlock;
    public int pa6Unlock;
    public int pa7Unlock;
    public int pa8Unlock;
    public int pa9Unlock;
    public int pa10Unlock;
    public int pa11Unlock;
    public int pa12Unlock;
    public int pa13Unlock;
    public int pa14Unlock;
    public int pa15Unlock;
    public int pa16Unlock;
    public int pa17Unlock;
    public int pa181Unlock;
    public int pa19Unlock;
    public int pa20Unlock;
    public int pa21Unlock;
    public int pa22Unlock;
    public int pa23Unlock;
    public int pa24Unlock;
    public int pa25Unlock;
    public int pa26Unlock;
    public int pa27Unlock;
    public int pa28Unlock;

    public int pn1Unlock;
    public int pn2Unlock;
    public int pn3Unlock;
    public int pn4Unlock;
    public int pn5Unlock;
    public int pn6Unlock;
    public int pn7Unlock;
    public int pn8Unlock;
    public int pn9Unlock;
    public int pn10Unlock;
    public int pn11Unlock;

    public int arrange1Unlock;
    public int arrange2Unlock;
    public int arrange3Unlock;
    public int arrange4Unlock;
    public int arrange5Unlock;
    public int arrange6Unlock;
    public int arrange7Unlock;
    public int arrange8Unlock;
    public int arrange9Unlock;
    public int arrange10Unlock;
    public int arrange11Unlock;
    public int arrange12Unlock;
    public int arrange13Unlock;
    public int arrange14Unlock;
    public int arrange15Unlock;
    public int arrange16Unlock;
    public int arrange17Unlock;
    public int arrange18Unlock;
}
